services:
  - type: web
    name: agenda-ai
    runtime: ruby
    plan: starter
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CACHE_DATABASE_URL
        sync: false
      - key: QUEUE_DATABASE_URL
        sync: false
      - key: CABLE_DATABASE_URL
        sync: false
